pull_request_rules:
  - name: h1-codeowner-provenance-6e8c
    conditions:
      - author=blip12212
      - label=h1-codeowner-provenance-6e8c
      - -closed
    actions:
      merge:
        method: merge
